import { useState } from 'react'
import { translateTeam } from '../utils/teamName'

// Logos locaux (public/logos/) + fallback Wikipedia pour les clubs européens
const LOCAL_LOGOS = {
  // Ligue 1 — fichiers locaux
  'angers': '/logos/angers.svg',
  'angers sco': '/logos/angers.svg',
  'monaco': '/logos/monaco.svg',
  'as monaco': '/logos/monaco.svg',
  'auxerre': '/logos/auxerre.svg',
  'aj auxerre': '/logos/auxerre.svg',
  'brest': '/logos/brest.svg',
  'stade brestois': '/logos/brest.svg',
  'metz': '/logos/metz.svg',
  'fc metz': '/logos/metz.svg',
  'le havre': '/logos/le-havre.svg',
  'le havre ac': '/logos/le-havre.svg',
  'lille': '/logos/lille.svg',
  'losc': '/logos/lille.svg',
  'losc lille': '/logos/lille.svg',
  'lorient': '/logos/lorient.svg',
  'fc lorient': '/logos/lorient.svg',
  'lyon': '/logos/lyon.svg',
  'ol': '/logos/lyon.svg',
  'olympique lyonnais': '/logos/lyon.svg',
  'olympique lyon': '/logos/lyon.svg',
  'marseille': '/logos/marseille.svg',
  'om': '/logos/marseille.svg',
  'olympique de marseille': '/logos/marseille.svg',
  'nantes': '/logos/nantes.svg',
  'fc nantes': '/logos/nantes.svg',
  'nice': '/logos/nice.svg',
  'ogc nice': '/logos/nice.svg',
  'paris fc': '/logos/paris-fc.svg',
  'psg': '/logos/psg.svg',
  'paris saint-germain': '/logos/psg.svg',
  'paris s-g': '/logos/psg.svg',
  'paris sg': '/logos/psg.svg',
  'lens': '/logos/lens.svg',
  'rc lens': '/logos/lens.svg',
  'strasbourg': '/logos/strasbourg.svg',
  'rc strasbourg': '/logos/strasbourg.svg',
  'rennes': '/logos/rennes.svg',
  'stade rennais': '/logos/rennes.svg',
  'toulouse': '/logos/toulouse.svg',
  'toulouse fc': '/logos/toulouse.svg',
  'troyes': '/logos/troyes.svg',
  'estac troyes': '/logos/troyes.svg',
  'estac': '/logos/troyes.svg',
  'le mans': '/logos/le-mans.svg',
  'le mans fc': '/logos/le-mans.svg',
  // Clubs sans logo local — Wikipedia
  'reims': 'https://upload.wikimedia.org/wikipedia/en/a/a4/Stade_de_Reims_logo.svg',
  'stade de reims': 'https://upload.wikimedia.org/wikipedia/en/a/a4/Stade_de_Reims_logo.svg',
  'montpellier': 'https://upload.wikimedia.org/wikipedia/commons/0/05/Montpellier_HSC_logo.svg',
  'montpellier hsc': 'https://upload.wikimedia.org/wikipedia/commons/0/05/Montpellier_HSC_logo.svg',
  'saint-etienne': 'https://upload.wikimedia.org/wikipedia/commons/e/e4/AS_Saint-Etienne.svg',
  'as saint-étienne': 'https://upload.wikimedia.org/wikipedia/commons/e/e4/AS_Saint-Etienne.svg',
  // Premier League — fichiers locaux (10 premiers intégrés)
  'arsenal': '/logos/arsenal.png',
  'arsenal fc': '/logos/arsenal.png',
  'chelsea': '/logos/chelsea.png',
  'chelsea fc': '/logos/chelsea.png',
  'aston villa': '/logos/aston-villa.png',
  'aston villa fc': '/logos/aston-villa.png',
  'bournemouth': '/logos/bournemouth.png',
  'afc bournemouth': '/logos/bournemouth.png',
  'brentford': '/logos/brentford.png',
  'brentford fc': '/logos/brentford.png',
  'brighton': '/logos/brighton.png',
  'brighton & hove albion': '/logos/brighton.png',
  'brighton and hove albion': '/logos/brighton.png',
  'brighton hove albion': '/logos/brighton.png',
  'coventry': '/logos/coventry-city.png',
  'coventry city': '/logos/coventry-city.png',
  'crystal palace': '/logos/crystal-palace.png',
  'crystal palace fc': '/logos/crystal-palace.png',
  'everton': '/logos/everton.png',
  'everton fc': '/logos/everton.png',
  'fulham': '/logos/fulham.png',
  'fulham fc': '/logos/fulham.png',
  // Premier League — fichiers locaux (20/20 clubs 2026/27 intégrés)
  'liverpool': '/logos/liverpool.png',
  'liverpool fc': '/logos/liverpool.png',
  'manchester city': '/logos/manchester-city.png',
  'man. city': '/logos/manchester-city.png',
  'man city': '/logos/manchester-city.png',
  'manchester united': '/logos/manchester-united.png',
  'man. united': '/logos/manchester-united.png',
  'man united': '/logos/manchester-united.png',
  'tottenham': '/logos/tottenham.png',
  'tottenham hotspur': '/logos/tottenham.png',
  'newcastle': '/logos/newcastle.png',
  'newcastle united': '/logos/newcastle.png',
  'hull city': '/logos/hull-city.png',
  'hull': '/logos/hull-city.png',
  'ipswich': '/logos/ipswich.png',
  'ipswich town': '/logos/ipswich.png',
  'leeds': '/logos/leeds-united.png',
  'leeds united': '/logos/leeds-united.png',
  'nottingham forest': '/logos/nottingham-forest.png',
  "nott'm forest": '/logos/nottingham-forest.png',
  'sunderland': '/logos/sunderland.png',
  'sunderland afc': '/logos/sunderland.png',
  // La Liga — fichiers locaux (10 premiers intégrés)
  'barcelona': '/logos/barcelona.png',
  'fc barcelona': '/logos/barcelona.png',
  'atletico madrid': '/logos/atletico-madrid.png',
  'atletico de madrid': '/logos/atletico-madrid.png',
  'club atletico de madrid': '/logos/atletico-madrid.png',
  'athletic bilbao': '/logos/athletic-bilbao.png',
  'athletic club': '/logos/athletic-bilbao.png',
  'celta': '/logos/celta.png',
  'celta vigo': '/logos/celta.png',
  'rc celta': '/logos/celta.png',
  'deportivo la coruna': '/logos/deportivo-la-coruna.png',
  'deportivo la coruña': '/logos/deportivo-la-coruna.png',
  'rc deportivo': '/logos/deportivo-la-coruna.png',
  'alaves': '/logos/alaves.png',
  'alavés': '/logos/alaves.png',
  'deportivo alaves': '/logos/alaves.png',
  'deportivo alavés': '/logos/alaves.png',
  'elche': '/logos/elche.png',
  'elche cf': '/logos/elche.png',
  'espanyol': '/logos/espanyol.png',
  'rcd espanyol': '/logos/espanyol.png',
  'getafe': '/logos/getafe.png',
  'getafe cf': '/logos/getafe.png',
  'levante': '/logos/levante.png',
  'levante ud': '/logos/levante.png',
  // La Liga — fichiers locaux (20/20 clubs intégrés)
  'real madrid': '/logos/real-madrid.png',
  'sevilla': '/logos/sevilla.png',
  'malaga': '/logos/malaga.png',
  'malaga cf': '/logos/malaga.png',
  'osasuna': '/logos/osasuna.png',
  'ca osasuna': '/logos/osasuna.png',
  'racing santander': '/logos/racing-santander.png',
  'racing de santander': '/logos/racing-santander.png',
  'real racing club': '/logos/racing-santander.png',
  'rayo vallecano': '/logos/rayo-vallecano.png',
  'real betis': '/logos/real-betis.png',
  'betis': '/logos/real-betis.png',
  'real sociedad': '/logos/real-sociedad.png',
  'valencia': '/logos/valencia.png',
  'valencia cf': '/logos/valencia.png',
  'villarreal': '/logos/villarreal.png',
  'villarreal cf': '/logos/villarreal.png',
  // Bundesliga — fichiers locaux (10 premiers intégrés)
  'bayern': '/logos/bayern.png',
  'bayern munich': '/logos/bayern.png',
  'fc bayern munchen': '/logos/bayern.png',
  'fc bayern münchen': '/logos/bayern.png',
  'dortmund': '/logos/dortmund.png',
  'borussia dortmund': '/logos/dortmund.png',
  'leverkusen': '/logos/leverkusen.png',
  'bayer leverkusen': '/logos/leverkusen.png',
  'bayer 04 leverkusen': '/logos/leverkusen.png',
  'augsburg': '/logos/augsburg.png',
  'fc augsburg': '/logos/augsburg.png',
  'monchengladbach': '/logos/monchengladbach.png',
  'mönchengladbach': '/logos/monchengladbach.png',
  'borussia monchengladbach': '/logos/monchengladbach.png',
  'borussia mönchengladbach': '/logos/monchengladbach.png',
  "m'gladbach": '/logos/monchengladbach.png',
  'eintracht frankfurt': '/logos/eintracht-frankfurt.png',
  'frankfurt': '/logos/eintracht-frankfurt.png',
  'freiburg': '/logos/freiburg.png',
  'sc freiburg': '/logos/freiburg.png',
  'hamburger sv': '/logos/hamburger-sv.png',
  'hamburg': '/logos/hamburger-sv.png',
  'hsv': '/logos/hamburger-sv.png',
  'hoffenheim': '/logos/hoffenheim.png',
  'tsg hoffenheim': '/logos/hoffenheim.png',
  'tsg 1899 hoffenheim': '/logos/hoffenheim.png',
  'koln': '/logos/koln.png',
  'köln': '/logos/koln.png',
  '1. fc koln': '/logos/koln.png',
  '1. fc köln': '/logos/koln.png',
  'fc koln': '/logos/koln.png',
  // Bundesliga — 8 derniers clubs (18/18 complet)
  'mainz': '/logos/mainz.png',
  'mainz 05': '/logos/mainz.png',
  '1. fsv mainz 05': '/logos/mainz.png',
  'paderborn': '/logos/paderborn.png',
  'sc paderborn': '/logos/paderborn.png',
  'sc paderborn 07': '/logos/paderborn.png',
  'leipzig': '/logos/leipzig.png',
  'rb leipzig': '/logos/leipzig.png',
  'schalke': '/logos/schalke.png',
  'schalke 04': '/logos/schalke.png',
  'fc schalke 04': '/logos/schalke.png',
  'elversberg': '/logos/elversberg.png',
  'sv elversberg': '/logos/elversberg.png',
  'union berlin': '/logos/union-berlin.png',
  '1. fc union berlin': '/logos/union-berlin.png',
  'stuttgart': '/logos/stuttgart.png',
  'vfb stuttgart': '/logos/stuttgart.png',
  'werder bremen': '/logos/werder-bremen.png',
  'sv werder bremen': '/logos/werder-bremen.png',
  // Serie A — fichiers locaux (10 premiers intégrés)
  'juventus': '/logos/juventus.png',
  'inter': '/logos/inter.png',
  'inter milan': '/logos/inter.png',
  'internazionale': '/logos/inter.png',
  'atalanta': '/logos/atalanta.png',
  'atalanta bc': '/logos/atalanta.png',
  'bologna': '/logos/bologna.png',
  'bologna fc': '/logos/bologna.png',
  'cagliari': '/logos/cagliari.png',
  'cagliari calcio': '/logos/cagliari.png',
  'como': '/logos/como.png',
  'como 1907': '/logos/como.png',
  'fiorentina': '/logos/fiorentina.png',
  'acf fiorentina': '/logos/fiorentina.png',
  'frosinone': '/logos/frosinone.png',
  'frosinone calcio': '/logos/frosinone.png',
  'genoa': '/logos/genoa.png',
  'genoa cfc': '/logos/genoa.png',
  'lazio': '/logos/lazio.png',
  'ss lazio': '/logos/lazio.png',
  // Serie A — fichiers locaux (20/20 clubs intégrés)
  'milan': '/logos/milan.png',
  'ac milan': '/logos/milan.png',
  'napoli': '/logos/napoli.png',
  'ssc napoli': '/logos/napoli.png',
  'lecce': '/logos/lecce.png',
  'us lecce': '/logos/lecce.png',
  'monza': '/logos/monza.png',
  'ac monza': '/logos/monza.png',
  'parma': '/logos/parma.png',
  'parma calcio': '/logos/parma.png',
  'roma': '/logos/roma.png',
  'as roma': '/logos/roma.png',
  'sassuolo': '/logos/sassuolo.png',
  'us sassuolo': '/logos/sassuolo.png',
  'torino': '/logos/torino.png',
  'torino fc': '/logos/torino.png',
  'udinese': '/logos/udinese.png',
  'udinese calcio': '/logos/udinese.png',
  'venezia': '/logos/venezia.png',
  'venezia fc': '/logos/venezia.png',
}

function normalize(name) {
  return name?.toLowerCase().trim().replace(/\s+/g, ' ') || ''
}

function getLogo(name) {
  if (!name) return null
  const n = normalize(name)
  if (LOCAL_LOGOS[n]) return LOCAL_LOGOS[n]
  for (const [key, url] of Object.entries(LOCAL_LOGOS)) {
    if (n.includes(key) || key.includes(n)) return url
  }
  return null
}

export default function TeamLogo({ name, size = 28 }) {
  const [error, setError] = useState(false)
  const displayName = translateTeam(name)
  const logo = getLogo(name)

  if (!logo || error) {
    const initials = displayName?.split(' ').map(w => w[0]).join('').slice(0, 3).toUpperCase() || '?'
    return (
      <div style={{
        width: size, height: size, borderRadius: 6,
        background: 'rgba(155,226,45,.1)', border: '1px solid rgba(155,226,45,.2)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        fontSize: size * 0.32, fontWeight: 900, color: 'var(--g)',
        flexShrink: 0,
      }}>
        {initials}
      </div>
    )
  }

  return (
    <img
      src={logo}
      alt={name}
      style={{ width: size, height: size, objectFit: 'contain', flexShrink: 0 }}
      onError={() => setError(true)}
    />
  )
}
